"""Plot progressive period degradation for a single Shor's case.

For a chosen (base, N, exp_bits) case, reads the approximated .tt files
generated by shor_e2e.py at each eb and shows three views of how the
period structure decays:

  1. f̃(x) sequence — first few periods, one line per eb
  2. Period autocorrelation C(r) vs r — one line per eb, with vertical
     lines at integer multiples of the true period r*
  3. QFT |amp|² spectrum for the largest f-value class — peaks around
     j = k·L/r* broaden as eb grows

Intended for telling the story of "what approximation does to the period".
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "third-party" / "qlut-benchmarks" / "src"))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from truthTable import TruthTable
from shor_lib import decode_f_values, period_autocorrelation


def load_f_at_eb(case_dir: Path, base: int, N: int, eb: float) -> list[int]:
    """Load f̃(x) at eb from either monolithic .tt or chained f-dump JSON."""
    mono = case_dir / f"approx_narrow_{base}_{N}_eb{eb}.tt"
    if mono.exists():
        return decode_f_values(TruthTable.from_file(str(mono)))
    chained = case_dir / f"chained_eb{eb}.f.json"
    if chained.exists():
        import json as _json
        data = _json.loads(chained.read_text())
        return data["approx_f"]
    raise FileNotFoundError(f"neither {mono} nor {chained}")


def plot_period_degradation(case: dict, case_dir: Path, out: Path,
                            cmap_name: str = "viridis") -> None:
    base = case["base"]
    N = case["N"]
    exp_bits = case["exp_bits"]
    L = 1 << exp_bits
    r_star = case["exact_period"]

    ebs = sorted({r["eb"] for r in case["sweep"] if not r.get("failed")})
    cmap = plt.get_cmap(cmap_name)
    colors = [cmap(i / max(1, len(ebs) - 1)) for i in range(len(ebs))]

    fig, axes = plt.subplots(3, 1, figsize=(10, 10))

    show_span = min(L, 4 * r_star)
    ax = axes[0]
    for i, eb in enumerate(ebs):
        f = load_f_at_eb(case_dir, base, N, eb)
        ax.plot(range(show_span), f[:show_span],
                marker="o", ms=3, lw=0.8,
                color=colors[i], label=f"eb={eb}")
    for k in range(0, show_span, r_star):
        ax.axvline(k, color="gray", lw=0.5, alpha=0.4)
    ax.set_title(
        f"(base={base}, N={N}, exp_bits={exp_bits}): "
        f"f̃(x) = {base}^x mod {N} (first {show_span} of 2^{exp_bits}), "
        f"true period r*={r_star}")
    ax.set_xlabel("x")
    ax.set_ylabel("f̃(x)")
    ax.legend(fontsize=7, ncol=3, loc="upper right")
    ax.grid(True, alpha=0.3)

    ax = axes[1]
    r_max = min(L - 1, 4 * r_star)
    for i, eb in enumerate(ebs):
        f = load_f_at_eb(case_dir, base, N, eb)
        corrs = [period_autocorrelation(f, r) for r in range(1, r_max + 1)]
        ax.plot(range(1, r_max + 1), corrs,
                color=colors[i], lw=1.0, label=f"eb={eb}")
    for k in range(r_star, r_max + 1, r_star):
        ax.axvline(k, color="red", lw=0.8, alpha=0.5, ls="--")
    ax.axvline(r_star, color="red", lw=0.8, alpha=0.5, ls="--",
               label=f"r* and multiples")
    ax.set_title("Period autocorrelation C(r) (higher at r=k·r* = strong period)")
    ax.set_xlabel("lag r")
    ax.set_ylabel(r"C(r) = Pr[$\tilde{f}(x) = \tilde{f}(x+r)$]")
    ax.set_ylim(0, 1.05)
    ax.legend(fontsize=7, ncol=3, loc="upper right")
    ax.grid(True, alpha=0.3)

    ax = axes[2]
    for i, eb in enumerate(ebs):
        f = load_f_at_eb(case_dir, base, N, eb)
        arr = np.array(f)
        vals, counts = np.unique(arr, return_counts=True)
        v = int(vals[np.argmax(counts)])
        mask = arr == v
        k = int(mask.sum())
        indicator = np.zeros(L, dtype=np.float64)
        indicator[mask] = 1.0 / math.sqrt(k)
        amp = np.fft.fft(indicator) / math.sqrt(L)
        prob = np.abs(amp) ** 2
        prob = prob / prob.sum()
        j_plot = min(L, 4 * (L // r_star) + 1)
        ax.plot(range(j_plot), prob[:j_plot],
                color=colors[i], lw=0.8, label=f"eb={eb}")
    peak_js = [k * L // r_star for k in range(1, 4 * L // r_star)]
    for j in peak_js:
        if j < j_plot:
            ax.axvline(j, color="red", lw=0.6, alpha=0.4, ls="--")
    ax.set_yscale("log")
    ax.set_title(
        f"QFT |amp(j)|² after measuring largest f-class "
        f"(ideal peaks at j = k·{L}/{r_star})")
    ax.set_xlabel("j (QFT index)")
    ax.set_ylabel("|amp(j)|²  (log)")
    ax.legend(fontsize=7, ncol=3, loc="upper right")
    ax.grid(True, alpha=0.3, which="both")

    fig.tight_layout()
    fig.savefig(out, dpi=140)
    print(f"wrote {out}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", type=Path,
        default=PROJECT_ROOT / "results" / "shor_quant" / "shor_e2e.json")
    ap.add_argument("--case", type=str, default="3,35,8",
        help="case selector base,N,exp_bits")
    ap.add_argument("--out", type=Path,
        default=PROJECT_ROOT / "results" / "shor_quant" / "plots" / "period_degradation.png")
    args = ap.parse_args()

    import json
    cases = json.loads(args.input.read_text())
    b, N, e = (int(x) for x in args.case.split(","))
    case = next((c for c in cases
                 if c["base"] == b and c["N"] == N and c["exp_bits"] == e), None)
    if case is None:
        raise SystemExit(f"case {args.case} not in {args.input}")
    if case.get("flavor") == "chained_windowed":
        case_dir = args.input.parent / f"case_{b}_{N}_w{case['w']}_m{case['m_total']}"
    else:
        case_dir = args.input.parent / f"case_{b}_{N}_{e}"
    plot_period_degradation(case, case_dir, args.out)


if __name__ == "__main__":
    main()
